name: my_cinemas
description: A movie ticket booking app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animations: ^1.1.2
  splashscreen: ^1.3.5
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.11.0
  firebase_core: ^0.7.0
  rating_bar: ^0.2.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  shared_preferences: ^0.5.12+4
  dio: ^2.1.13
  bloc: ^3.0.0
  rxdart: ^0.23.1
  page_indicator: ^0.2.0
  url_launcher: ^5.7.10
  http: ^0.12.2
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/no-image.png
   - assets/images/logo.png
   - assets/images/poster.jpeg
   - assets/images/posters/america.jpeg
   - assets/images/posters/avengers.jpeg
   - assets/images/posters/matrix.jpeg
   - assets/images/posters/spider.jpeg
   - assets/images/posters/star.jpeg
   - assets/images/posters/us.jpeg
   - assets/images/trailers/jack.jpeg
   - assets/images/trailers/noname.jpeg
   - assets/images/trailers/thief.jpeg
   - assets/images/trailers/venom.jpeg
   - assets/images/trailers/xmen.jpeg
   - assets/images/upcoming/bazaar.jpeg
   - assets/images/upcoming/bhuj.jpeg
   - assets/images/upcoming/dhakad.jpeg
   - assets/images/upcoming/kapil.jpeg
   - assets/images/upcoming/replicas.jpeg
   - assets/images/upcoming/thugs.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Roboto
     fonts:
       - asset: assets/fonts/Roboto-Regular.ttf
       - asset: assets/fonts/Roboto-Medium.ttf
       - asset: assets/fonts/Roboto-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
